### ISSUE TITLE
Prometheus End Point Returns 401

### ISSUE THREAD

**Issue by ZirNeo** [spring-cloud-stream-app-starters/rabbit#28]
After setting up the properties 

- management.endpoints.web.exposure.include: prometheus,info,health
- spring.cloud.streamapp.security.enabled = false
- management.metrics.export.prometheus.enabled = true
- management.security.enabled = false

Whenever I try to access /actuator/prometheus gives 401 error and so far in only happens on the rabbit sink and source, any other starter reports to prometheus as intended.

**Comment by tzolov** [comment]
@ZirNeo , could you please share the version of the `rabbit` app you test with? 
Also is the `Rabbit` or `Kafka` binding?

**Comment by ZirNeo** [comment]
@tzolov Yeah sure 
rabbit-source-kafka:2.1.1.RELEASE
rabbit-sink-kafka:2.1.1.RELEASE

**Comment by tzolov** [comment]
Thanks @ZirNeo  
I reproduced the issue. It looks like a bug due to pom-plugin misconfigurations for the rabbit-source and rabbit-sink apps. Only the rabbit apps are affected. 
The fix PR is coming shortly

**Comment by tzolov** [comment]
Problem description: 
To solve a issue with CF (https://github.com/spring-cloud-stream-app-starters/rabbit/commit/d921fbe8e01a6aed079186458310a29821c97876) and remove the connector dependencies the Rabbit apps override the default `additionalGlobalDependencies` definitions in the [core](https://github.com/spring-cloud-stream-app-starters/core/blob/master/pom.xml#L177). 
The overridden `additionalGlobalDependencies` though is missing all metrics and security dependencies needed for the SCDF monitoring.

**Comment by tzolov** [comment]
Hi @ZirNeo, the PR is merged to the master. Could you try it to see if it resolves your issues? 
to build it for master just do:
```
 ./mvnw clean install -PgenerateApps -DskipTests
cd apps
mvn clean install
```
The use the scdf shell's app register to register the newly build jars from the file system (E.g with the `file:///<path to the jar on your machine>`
