### ISSUE TITLE
Improve source and sink connection factory creation.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud-stream-app-starters/rabbit#6]
In a PCF environment with auto-reconfiguration enabled and a rabbit service bound to the source and sink, the apps will always get the service bound to the app instead of what is specified in the source/sinks configuraiton properties.  This is due to 

```
	@ServiceActivator(inputChannel = Sink.INPUT)
	@Bean
	public MessageHandler amqpChannelAdapter(ConnectionFactory rabbitConnectionFactory) {
```
relying on asking for an existing `ConnectionFactory` that is in the application context, in this case the one created via auto-reconfiguration.

Based on the presence of the property `spring.rabbitmq.host` create a `ConnectionFactory` that is not a managed bean.

**Comment by garyrussell** [comment]
We can't use `host` - boot pre-populates it with `localhost`. I think we need a new boolean.

**Comment by sabbyanandan** [comment]
How about naming it `useExplicitConnection`, `createExplicitConnection`, or `useSuppliedConnection`?

**Comment by markpollack** [comment]
`newConnection` ?

**Comment by markpollack** [comment]
Nothing is great naming wise since it should be implied

**Comment by garyrussell** [comment]
Sorry - missed this discussion (heads-down coding); I went with `ownConnection`.
